development:
  google:
    token: <%= ENV['google_token'] %>
    key:   <%= ENV['google_key'] %>

production:
  google:
    token: <%= ENV['google_token'] %>
    key:   <%= ENV['google_key'] %>

test:
  google:
    token: <%= ENV['google_token'] %>
    key:   <%= ENV['google_key'] %>
